---

- hosts: all
  become: true
  tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (Centos)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
     

- hosts: all
  become: true
  tasks:

  - name: Create user Ansible
    tags: always
    user:
      name: ansible 
      groups: root

  - name: add ssh key for ansible
    tags: always
    authorized_key:
      user: ansible
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHpvSlaetFThqwkKS1NOs3kGS6pllJVmvKV816nsAqo4 Ansible 18.0"

  - name: add Sudoers file for ansible
    tags: always
    copy:
      src: sudoers_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440
